### ISSUE TITLE
Network traffic monitor

### ISSUE THREAD

**Issue by Mambo1818** [ltkhang/sdn-ids-ddos-defense#1]
Mr Itkhang,
Your code is wonderful. However, it is recommended to separate the network traffic capturing part and AI modelling part for easy assimilation of the product.
Regards

**Comment by ltkhang** [comment]
> Mr Itkhang,
> Your code is wonderful. However, it is recommended to separate the network traffic capturing part and AI modelling part for easy assimilation of the product.
> Regards

Hello Mambo1818,

This is my demo code for my undergraduate thesis which I am going to defending on Aug 2020 (Due to COVID-19 sucking, too late for defending).

As you can see, I separated the flow into multiple threads, that means, in the future, I can easily separate this application into multiple processes and link them together with somethings maybe like message brokers, etc.

I can not find anyone who has an interest in this topic, you know, DDoS defense, SDN in my class, that's why I had to complete this thesis with a-team-one-guy.

Therefore, don't hesitate to discuss more about this.

**Comment by Mambo1818** [comment]
Mr Itkhang,
I am also working on my dissertation only with regards to analysis network
traffic for malicious behaviour using AI models. I was trying to use
CICFlowmeter but uncomfortable with it as it is written in JAVA (which i
dont like). I am pretty comfortable with Python, that's why came across
your code. would surely like to contribute to your code. Will get in touch
for that soon.
Regards
