### ISSUE TITLE
Flowmeter for Python

### ISSUE THREAD

**Issue by swight-prc** [ltkhang/sdn-ids-ddos-defense#4]
@ltkhang , I saw your comment on the CIC Flowmeter site about duplicating it in Python.

Consider using https://github.com/prc-hsv/flowmeter instead of rewriting it. We've tried to duplicate CIC Flowmeter as reasonably as possible, and it seems to perform, but I would love to have another set of eyes. We actually started from https://github.com/alekzandr/flowmeter but it didn't have some features that we needed.

ETA: Software features, not data features

**Comment by ltkhang** [comment]
Hi, on the next few weeks, I am gonna start re-coding the whole CICFlowmeter in python. Besides, I will consider all of the issues from the original one to enhance in my code. I would like to re write my own, because I am working on a research paper that I should not rely on a developing-state library.

**Comment by swight-prc** [comment]
Sounds good. Have fun and good luck!

**Comment by aouinizied** [comment]
@swight-prc looks like you are trying to build what we already done within NFStream project. We did a lot of effort from a performance perspectives (not using scapy, multiprocessing, nDPI integration, etc)
Do you think it is possible to join our efforts in order to build a common framework for researchers which will improve reproducibility across experiements?
Feel free to contact us.

Github repository: https://github.com/nfstream/nfstream
Website: https://www.nfstream.org/

Regards

**Comment by ltkhang** [comment]
> @swight-prc looks like you are trying to build what we already done within NFStream project. We did a lot of effort from a performance perspectives (not using scapy, multiprocessing, nDPI integration, etc)
> Do you think it is possible to join our efforts in order to build a common framework for researchers which will improve reproducibility across experiements?
> Feel free to contact us.
> 
> Github repository: https://github.com/nfstream/nfstream
> Website: https://www.nfstream.org/
> 
> Regards

I am reading your framework and consider if your features could be useful for machine learning. Thank you.

**Comment by aouinizied** [comment]
@ltkhang it is designed for ML experiment as you can even deploy your model on live traffic by adding a Plugin (See the example)

**Comment by ltkhang** [comment]
> @ltkhang it is designed for ML experiment as you can even deploy your model on live traffic by adding a Plugin (See the example)

Yes, I have just read all of your APIs and it is kinda easy to use, I will do some experiments for network intrusion detection when I have time.
